name: Release latest version of the action
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Make a latest release of the action
    runs-on: ubuntu-latest
    steps:
      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
