name: Release latest version of the action
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Make a latest release of the action
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
